import streamlit as st

st.title("Employee Productivity (EP)")
st.divider()
st.write("""
**:green[Definition:]** Employee Productivity measures the efficiency of employees in generating output relative to the resources (like time or cost) invested. It is often calculated as the ratio of total output to total input (such as hours worked).

**:blue[Business Relevance:]** High employee productivity contributes to overall business efficiency and profitability, indicating that Olaplex is utilizing its workforce effectively to meet its goals. It helps in decision-making regarding staffing, operational costs, and performance improvement.

**:red[Formula:]** Employee Productivity can be calculated as:
""")
st.image("./assets/ep_formula.png")
st.divider()

st.write(":orange[Employee Productivity (EP) Playground]")

st.write("""
This calculator helps you estimate Employee Productivity (EP) based on the following inputs:
- **Total Output**: The total revenue or value generated by an employee or team over a given period.
- **Total Hours Worked**: The total number of hours worked by the employee or team over the same period.
""")

# Input fields
total_output = st.number_input("Total Output (Revenue or Value)", min_value=0.0, step=1.0, value=50000.0)
total_hours_worked = st.number_input("Total Hours Worked", min_value=0.0, step=1.0, value=1600.0)

# Employee Productivity calculation
employee_productivity = total_output / total_hours_worked

st.write(f"Employee Productivity = {employee_productivity:.2f} units per hour")

st.divider()

# Interpretation
st.write("""
**:violet[Interpretation]**:
- A **higher Employee Productivity** indicates that employees are contributing more value per hour worked, which is a sign of effective performance and efficient use of resources.
- A **lower Employee Productivity** may signal inefficiencies, underutilization of talent, or a need for performance improvements, such as better training or tools.
- Please consult with :red[Human Resources] to ensure that all communications remain respectful and free of unintended biases in the case of low employee productivity.
""")