import streamlit as st

st.title("Operating Margin (OM)")
st.divider()
st.write("""
**:green[Definition:]** Operating margin measures the percentage of revenue left after paying for variable costs of production, 
like wages and raw materials.

**:blue[Business Relevance:]** A higher operating margin indicates better efficiency in running the company's core operations.

**:red[Formula:]** Operating Margin is calculated as:
""")
st.image("./assets/om_formula.png")
st.divider()

st.write(":orange[Operating Margin (OM) Playground]")

st.write("""
In the formula:
- **Operating Income:** income from normal business operations, excluding interest and taxes.
- **Revenue:** total revenue generated by the company during the period.
""")

# Input fields for operating income and total revenue
operating_income = st.number_input("Operating Income", min_value=0.0, step=1.0, value=50000.0)
revenue = st.number_input("Total Revenue", min_value=0.0, step=1.0, value=200000.0)

# Operating Margin Calculation
operating_margin = (operating_income / revenue) * 100

# Display the Operating Margin result
st.write(f"Operating Margin = {operating_margin:.2f}%")

st.divider()

st.write("""**:violet[Interpretation:]**
- A **higher operating margin** indicates better operational efficiency and that the company is managing its costs well.
- A **lower operating margin** suggests the company may be struggling with its operational efficiency or facing high production costs.
""")