[theme]
# Primary accent color for interactive elements.
primaryColor = "#000000"

# Background color for the main content area.
backgroundColor = "rgb(14, 17, 23)"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "rgb(38, 39, 48)"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"